Footer finished
G-Gateway-React/ecommerca-team2 pull request #9
Opened 2022-08-01 07:36 UTC by maalyhesham

create footer section #1

2022-08-01 07:54 UTC, Yazan-kass reviewed
If you can turn it responsive

2022-08-23 08:32 UTC, Yazan-kass approved these changes

2022-08-29 17:28 UTC, Mossa-99 requested changes

2022-08-29 17:28 UTC, Mossa-99 commented on src/App.tsx
> +            <Route path='/'  /> */}
commented code

2022-08-29 17:28 UTC, Mossa-99 commented on src/components/Footer/index.tsx
> +    <FooterStyle>
please use prettier for code formatting
https://www.youtube.com/watch?v=h3PJjP0nE98

2022-08-29 17:28 UTC, Mossa-99 commented on src/components/Footer/index.tsx
> +            <AnchorLink to='/FAQ'> LEGAL Policies  </AnchorLink>
Please remove spaces in the text, you can add spaces and margins using css

2022-08-29 17:28 UTC, Mossa-99 commented on src/components/SingFooter/index.tsx
> +function SingFootersection() {
```suggestion
function SignInFooter() {
```
and if the footer is the same for the whole app, you can name it just ``Footer``

2022-08-29 18:08 UTC, Yazan-kass commented
Done

2022-08-30 09:19 UTC, closed without merging